# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csample.proto\"%\n\x04Test\x12\x0f\n\x07test_id\x18\x01 \x01(\t\x12\x0c\n\x04hoge\x18\x02 \x01(\t\"\xaf\x01\n\x05Multi\x12\x19\n\x04item\x18\x01 \x01(\x0b\x32\x0b.Multi.Item\x12\x1d\n\x06\x61ppend\x18\x02 \x03(\x0b\x32\r.Multi.Append\x1a\x33\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04hoge\x18\x02 \x01(\t\x12\x0c\n\x04\x66uga\x18\x03 \x01(\t\x1a\x37\n\x06\x41ppend\x12\x11\n\tappend_id\x18\x01 \x01(\t\x12\x0c\n\x04hoge\x18\x02 \x01(\x01\x12\x0c\n\x04\x66uga\x18\x03 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_id', full_name='Test.test_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoge', full_name='Test.hoge', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=53,
)


_MULTI_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Multi.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='Multi.Item.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoge', full_name='Multi.Item.hoge', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fuga', full_name='Multi.Item.fuga', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=174,
)

_MULTI_APPEND = _descriptor.Descriptor(
  name='Append',
  full_name='Multi.Append',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='append_id', full_name='Multi.Append.append_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoge', full_name='Multi.Append.hoge', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fuga', full_name='Multi.Append.fuga', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=231,
)

_MULTI = _descriptor.Descriptor(
  name='Multi',
  full_name='Multi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='Multi.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='append', full_name='Multi.append', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MULTI_ITEM, _MULTI_APPEND, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=231,
)

_MULTI_ITEM.containing_type = _MULTI
_MULTI_APPEND.containing_type = _MULTI
_MULTI.fields_by_name['item'].message_type = _MULTI_ITEM
_MULTI.fields_by_name['append'].message_type = _MULTI_APPEND
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['Multi'] = _MULTI

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  ))
_sym_db.RegisterMessage(Test)

Multi = _reflection.GeneratedProtocolMessageType('Multi', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _MULTI_ITEM,
    __module__ = 'sample_pb2'
    # @@protoc_insertion_point(class_scope:Multi.Item)
    ))
  ,

  Append = _reflection.GeneratedProtocolMessageType('Append', (_message.Message,), dict(
    DESCRIPTOR = _MULTI_APPEND,
    __module__ = 'sample_pb2'
    # @@protoc_insertion_point(class_scope:Multi.Append)
    ))
  ,
  DESCRIPTOR = _MULTI,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Multi)
  ))
_sym_db.RegisterMessage(Multi)
_sym_db.RegisterMessage(Multi.Item)
_sym_db.RegisterMessage(Multi.Append)


# @@protoc_insertion_point(module_scope)
